#Type Name    ID GECOS             Home directory            Shell
g     miw     -  -                 -                         -
u     usbmon  -  "usbmon-exporter" /var/lib/usbmon-exporter  /sbin/nologin
m     usbmon  miw
